version: 2.1
description: "An orb for Zappa, the Python serverless framework"

executors:
  default:
    docker:
      - image: circleci/python:2.7

  python:
    parameters:
      version:
        type: "string"
        default: "2.7"
    docker:
      - image: circleci/python:<<parameters.version>>

commands:
  deploy-or-update:
    parameters:
      stage:
        type: string
        default: "dev"
    steps:
      - run:
          name: Deploying to << parameters.stage >>
          command: |
            set +e
            STATUS=$(pipenv run zappa status << parameters.stage >> -j 2>&1)
            set -e
            if [[ $(echo $STATUS | jq . 2>/dev/null) ]];
            then pipenv run zappa update << parameters.stage >>;
            elif [[ "$STATUS" == *"have you deployed yet?" ]];
            then pipenv run zappa deploy << parameters.stage >>;
            else echo "$STATUS\nUnknown error!" && exit 1
            fi

jobs:
  zappa-deploy:
    executor: default
    parameters:
      stage:
        type: string
        default: "dev"

    steps:
      - checkout
      - run: pipenv install
      - deploy-or-update:
          stage: << parameters.stage >>
