version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.2
  orb-tools: circleci/orb-tools@7

commands:
  prepare_test:
    parameters:
      case:
        type: string
    steps:
      - run:
          name: Prepare test case << parameters.case >>
          command: |-
            circleci config process \
            tests/unit/manifest/<< parameters.case >>.yml > << parameters.case >>.yml
      - store_artifacts:
          path: << parameters.case >>.yml

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - cli/install
      - checkout
      - run: pipenv install --dev
      - prepare_test:
          case: simple
      - prepare_test:
          case: executor
      - prepare_test:
          case: update_only
      - prepare_test:
          case: all_stages
      - run: pipenv run python -m unittest discover -s tests

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint:
          name: lint

      - orb-tools/pack:
          name: pack
          requires:
            - lint

      - orb-tools/publish:
          name: publish-test-channel
          attach-workspace: true
          checkout: false
          orb-ref: "borb/zappa@dev:test-channel"
          requires:
            - pack

      - orb-tools/publish:
          name: publish-branch-channel
          attach-workspace: true
          checkout: false
          orb-ref: "borb/zappa@dev:${CIRCLE_BRANCH}"
          requires:
            - pack

      - run_tests:
          name: "Compile test manifests and run tests"
          requires:
            - publish-test-channel
