version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint:
          name: lint

      - orb-tools/pack:
          name: pack
          requires:
            - lint

      - orb-tools/publish:
          name: publish
          attach-workspace: true
          checkout: false
          orb-ref: "borb/zappa@dev:${CIRCLE_BRANCH}"
          requires:
            - pack
