version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.2
  orb-tools: circleci/orb-tools@7

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.6
    steps:
      - cli/install
      - checkout
      - run: pipenv install --dev
      - run: circleci config process test/manifest/simple.yml > simple.yml
      - run: circleci config process test/manifest/executor.yml > executor.yml
      - run: circleci config process test/manifest/update_only.yml > update_only.yml
      - store_artifacts:
          path: simple.yml
      - store_artifacts:
          path: executor.yml
      - store_artifacts:
          path: update_only.yml
      - run: pipenv run python -m unittest test

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint:
          name: lint

      - orb-tools/pack:
          name: pack
          requires:
            - lint

      - orb-tools/publish:
          name: publish-test-channel
          attach-workspace: true
          checkout: false
          orb-ref: "borb/zappa@dev:test-channel"
          requires:
            - pack

      - orb-tools/publish:
          name: publish-branch-channel
          attach-workspace: true
          checkout: false
          orb-ref: "borb/zappa@dev:${CIRCLE_BRANCH}"
          requires:
            - pack

      - run_tests:
          name: "Compile test manifests and run tests"
          requires:
            - publish-test-channel
