description: >
  Deploy the master branch to the Zappa 'dev' stage.

version: 2.1

orbs:
  zappa: borb/zappa@dev:master

jobs:
  - zappa/zappa-deploy:
      stage: "dev"
      filters:
        branches:
          only: master
